# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master # Branch is named Effera in Github

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build
  displayName: 'npm install, increment version and build'
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'dist/@ngx-formly/core'
    publishRegistry: 'useFeed'
    publishFeed: '770d96be-9346-4e8d-9d86-2b37a0e9deb0'
    displayName: 'publish @ngx-formly/core'

- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'dist/@ngx-formly/material'
    publishRegistry: 'useFeed'
    publishFeed: '770d96be-9346-4e8d-9d86-2b37a0e9deb0'
    displayName: 'publish @ngx-formly/material'
- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'dist/@ngx-formly/schematics'
    publishRegistry: 'useFeed'
    publishFeed: '770d96be-9346-4e8d-9d86-2b37a0e9deb0'
    displayName: 'publish @ngx-formly/schematics'
